### ISSUE TITLE
TACO Project (Ubuntu 18.04) issue

### ISSUE THREAD

**Issue by jjhhong** [openinfradev/tacoplay#10]
**Describe the bug**
현재 해당 프로젝트 우분투 18.04 버전에서 빌드 에러가 발생합니다. 
**To Reproduce**
1. 020-install-k8s.sh 실행
2. docker project 18.04버전 미지원으로 인해 다운로드 관련 에러 발생
3. See error

fatal: [taco-aio]: FAILED! => {"changed": "false", "msg"" "Failed to update apt cache: E:https://apt.dockerproject.org/repo/dists/ubuntu-bionic/InRelease 파일을 받는데 실패했습니다 403 Fobidden [IP: 54.230.181.205 443], E:The repository 'https://apt.dockerproject.org/repo/dists/ubuntu-bionic InRelease' is not signed."}

**Expected behavior**
다음 프로세스 진행이 불가함.

**Desktop (please complete the following information):**
 - OS: Ubuntu
 - Browser :
 - Version 18.04

**Comment by bluejayKR** [comment]
우선 현재 버전의 tacoplay에서는 Ubuntu OS상에서의 설치를 지원하지 않습니다. 
현재 팀 내부에서 테스트 중이며, 빠른 시일내로 Ubuntu 에서 설치 가능한 버전으로 릴리즈할 예정입니다. 

업데이트 할 내용이 있으면 담당 개발자분을 통해서 공유토록 하겠습니다.

**Comment by thaJeztah** [comment]
The apt.dockerproject.org repository is deprecated, and replaced by download.docker.com, which has packages for current distro-versions and current docker releases. Installation instructions for Ubuntu can be found here; https://docs.docker.com/install/linux/docker-ce/ubuntu/
