### ISSUE TITLE
PR/Issue에 대한 lifecycle 관리 방안 

### ISSUE THREAD

**Issue by bluejayA** [openinfradev/tacoplay#100]
현황

현재 github action을 통해서, stale label을 자동으로 적용하고 close되는 기준이 적용되어 있음. 
stale 이 붙은 이후에 각 PR/Issue의 특성에 따라 좀 더 세부적인 구분이 가능했으면 함. 

참고로 kubernetes에서는 PR/Issue에 대해서 아래와 같이 네 단계로 관리하고 있는 것으로 보임\
lifecycle/active, lifecycle/stale, lifecycle/frozen, lifecycle/rotten.. 

따라서, 우리도 이를 차용하여 lifecycle/active, lifecycle/stale, lifecycle/frozen 정도로 운영하면 어떨까 생각하며, 만약 동의된다면 github action의 설정을 이에 맞추어 현행화가 필요함 

_Originally posted by @bluejayA in https://github.com/openinfradev/tacoplay/issues/84#issuecomment-865638914_

**Comment by bluejayA** [comment]
@Jaesang @jabbukka 님 의견 부탁드려요. 
목적은 close상태로 변경되는 PR/이슈중에서 백로그로 남겨두고, 나중에 가능할때 다시 reopen 해야 하는 대상을 구분하고 싶다. 입니다만 (제 기준으로는) 

Kubernetes 커뮤니티에서는 frozen과 rotten을 사용해서 유사한 구분을 하는 듯 하네요. stale 된 애들을 담당자가 보고 판단해서 둘 중에 하나를 붙이면, close 되더라도 향 후 쉽게 구분 가능할 것 같습니다. 

추가로, label 관리 차원에서는 kubernetes에서 쓰는 lifecycle/stale, lifecycle/frozen 등으로 하는 것도 좋지 않을까 하구요.

**Comment by Jaesang** [comment]
네, stale -> closed 사이에 rotten을 두고 frozen label이 수동으로 붙여지면 해당 이슈는 자동 close에서 제외되도록 하면 좋을 것 같습니다.
lifecycle/을 접두로 붙이는것도 이해하기 더 좋아보입니다.

**Comment by bluejayA** [comment]
에스더님이 이 action을 쓰신것 같은데 https://github.com/marketplace/actions/close-stale-issues, 여기서 stale이 붙은 후에 특정 label을 추가하면 close가 안되게 하는 옵션이 있으려나 모르겠네요. 

exempt-pr-labels 가 workflow 중간에 들어가도 작동하려나요?
