### ISSUE TITLE
Taco 설치 중 에러가 생겨 문의드립니다.

### ISSUE THREAD

**Issue by yrkim1018** [openinfradev/tacoplay#11]
안녕하세요. 

현재 저는 아래와 같은 환경에서 타코를 설치하고 있습니다.

![상황설명](https://user-images.githubusercontent.com/57470862/68357246-091f0880-0158-11ea-96bb-959597adc9ed.PNG)

KVM이 설치된 우분투에서 centos가 설치된  VM을 생성해 그 위에 타코를 설치하는 것인데요.
설치가이드를 따라 하던 중 ansible-playbook을 실행할 때 에러가 발생했습니다.
armada.log 파일과 설치할 때 나타난 에러 화면은 아래와 같습니다.

키스톤 관련해서 문제가 발생하는 것 같은데요.. 
이 문제를 어떻게 해결할 수 있을까요? 

<armada.log 내용>
![armada1](https://user-images.githubusercontent.com/57470862/68357354-674beb80-0158-11ea-8db9-7695567d658b.PNG)
![armada2](https://user-images.githubusercontent.com/57470862/68357360-69ae4580-0158-11ea-9b07-7e7b678ac604.PNG)
![armada3](https://user-images.githubusercontent.com/57470862/68357366-716dea00-0158-11ea-9849-d5a9a2793efa.PNG)

<에러 화면>
![에러화면](https://user-images.githubusercontent.com/57470862/68357372-76cb3480-0158-11ea-981d-f8f2fc3185ec.PNG)

<설치된 pod 현황>
![pod 현황](https://user-images.githubusercontent.com/57470862/68357373-7a5ebb80-0158-11ea-9533-656a019e378e.PNG)

**Comment by Jaesang** [comment]
현재 19.03 브랜치에 대한 개발이 끝나지 않은 상태라 정상 실행할 수가 없습니다. 19.02 브랜치를 사용하시면 괜찮습니다.
