### ISSUE TITLE
Rook-Ceph 의 cluster.yaml 변경사항 

### ISSUE THREAD

**Issue by prudentcircle** [openinfradev/tacoplay#120]
안녕하세요!

지난주 , 07/23(금) 일자로 TACOPLAY v21.06 branch를 다운 받아 TACOPLAY 설치를 진행했는데요,
아래 cluster.yaml에 추가해주셨던 내용이 제대로 반영이 안 되었는지,
TACOPLAY 실행시에 MON 생성과 OSD 생성이 제대로 되지 않았던 Issue 발견 되었습니다.

```
+  placement:
+    all:
+      nodeAffinity:
+        requiredDuringSchedulingIgnoredDuringExecution:
+          nodeSelectorTerms:
+          - matchExpressions:
+            - key: role
+              operator: In
+              values:
+              - storage-node
+      tolerations:
+      - key: storage-node
+        operator: Exists
```

# 2. Workaround

지난 금요일 기준으로  tacoplay/charts/taco-helm-charts/rook-ceph-cluster/templates/cluster.yaml 에 위 반영 해주신 내용이 없는것을 확인하였습니다.

일단 TACOPLAY로 설치된 rook-ceph-cluster를 helm delete 한 후, 
제가 manual 하게 cluster.yaml에 해당 내용을 추가한 후, site.yaml 다시 실행하여 설치 진행하였습니다.

정상적으로 설치 되는것을 확인하였습니다.

**Comment by zugwan** [comment]
https://github.com/openinfradev/helm-charts/tree/main/rook-ceph-cluster 차트에는 스케쥴링 관련 내용이 아직 포함되어 있지 않습니다. 추가하도록 하겠습니다.

**Comment by prudentcircle** [comment]
> https://github.com/openinfradev/helm-charts/tree/main/rook-ceph-cluster 차트에는 스케쥴링 관련 내용이 아직 포함되어 있지 않습니다. 추가하도록 하겠습니다.

감사합니다! 추가 해 주시면, site.yaml 실행만으로 rook-ceph가 성공적으로 설치 되는지 확인해 보겠습니다. 
(1-2개월 후에 또 군데 더 설치가 필요해서, 그 때 확인 진행할 수 있을것 같습니다.)

**Comment by prudentcircle** [comment]
타이밍 맞게 Open 해 주셨네요! 이틀 뒤에 TACOPLAY를 Clone 해서 OpenStack + Rook-Ceph 까지 배포 할 예정입니다.
혹시, 해당 사항이 조만간 반영이 되는걸까요?
