### ISSUE TITLE
rbd provisioner 컨테이너 이미지 태그

### ISSUE THREAD

**Issue by prudentcircle** [openinfradev/tacoplay#15]
Armada Manifest에서 ceph_rbd_provisioner로 사용되는 이미지가
현재 Docker Hub에 올라와 있는 sktdev/rbd-provisioner:v2.1.1-nautilus-14.2.4 이미지가 궁금합니다!

기존 네이밍은 아래와 같았는데요, 
{{docker_registry}}/openstackhelm/ceph-rbd-provisioner:ubuntu_bionic-20200217

네이밍만 살짝 다른건지, 아니면 완전히 다른 이미지인건지 궁금합니다!

**Comment by zugwan** [comment]
원래 사용하던 rbd_provisioner 이미지는 아래와 같이 quay에 저장된 것을 사용하고 있었고 사용한 Ceph 클라이언트 버전은 Luminous 였던 것으로 기억합니다.
 -> https://github.com/kubernetes-sigs/kubespray/blob/0c51352a74052455cc6014c5394eaf36316ddfda/roles/download/defaults/main.yml#L510

Ceph Nautilus 버전에서 muilti-mon 구성 시 하위 버전의 클라이언트가 접근이 안 되던 이슈가 있었기 때문에 위 이미지에서 Ceph 클라이언트 버전을 Nautilus 버전으로 변경해서 tag에 nautilus 를 추가해서 사용 중입니다.

**Comment by prudentcircle** [comment]
아아. 답변 감사드립니다.

KubeSpray에서 Default로 가져오는 rbd_provisioner 이미지는 Nautilus 버전과 호환성 이슈가 있어서 그러셨던 거군요. 그럼 Armada-Manifest 에서 사용하는 이미지는 아닌거네요. 

저는 OpenStack-Helm-Infra 내에 있는 Ceph-Provisioner에 명시된 ceph_rbd_provisioner와 잠깐 혼동 했었습니다. 두 개가 끝내는 같은 역할을 하지 않을까 하는 생각이 갑자기 드네요.
```
ceph_rbd_provisioner: 'docker.io/openstackhelm/ceph-rbd-provisioner:ubuntu_bionic-20200217'
```
이건 직접 설치해보면서 알아보겠습니다. ^^.
감사합니다~
