### ISSUE TITLE
TACOPLAY Release taco-v20.05 README file 현행화 필요 

### ISSUE THREAD

**Issue by bluejayKR** [openinfradev/tacoplay#19]
https://github.com/openinfradev/tacoplay/blob/taco-v20.05/README.md 를 v19.03 를 참조하여 현행화 할 필요가 있습니다. 

설치문서가  https://taco-docs.readthedocs.io/ko/latest/#에 작성된 이후에는 링크만 걸어주는 정도로 README를 만들었습니다.

**Comment by iksungjeon** [comment]
네, 금일 추가 minor 수정사항들과 함께 반영하여 최종본 master 에 업데이트하도록 하겠습니다.

**Comment by leopold9707** [comment]
https://github.com/openinfradev/taco-docs/pull/26

**Comment by bluejayKR** [comment]
This is done now.
