### ISSUE TITLE
Error from server (NotFound): endpoints

### ISSUE THREAD

**Issue by hycho96** [openinfradev/tacoplay#2]
안녕하세요.

tacoplay를 실행했더니 Error 가 나서 문의 드립니다.

- 환경 OS : CentOS-7-x86_64-DVD-1810
- 가상 VM(PC): 
git clone https://github.com/openinfradev/tacoplay.git 를 
아래 설명에 따라 https://docs-handson.readthedocs.io/en/latest/taco-aio.html#taco 실행했습니다.

그런데 아래와 같은 Error가 발생하네요.
===================================================================
TASK [openstack/client : update bashrc for openstack client configs] ********************************************************
Friday 09 August 2019  14:56:06 +0900 (0:01:41.836)       0:15:34.752 *********
changed: [taco-aio]

TASK [openstack/client : check host where ingress controller is running] ****************************************************
Friday 09 August 2019  14:56:06 +0900 (0:00:00.150)       0:15:34.902 *********
FAILED - RETRYING: check host where ingress controller is running (10 retries left).
FAILED - RETRYING: check host where ingress controller is running (9 retries left).
FAILED - RETRYING: check host where ingress controller is running (8 retries left).
FAILED - RETRYING: check host where ingress controller is running (7 retries left).
FAILED - RETRYING: check host where ingress controller is running (6 retries left).
FAILED - RETRYING: check host where ingress controller is running (5 retries left).
FAILED - RETRYING: check host where ingress controller is running (4 retries left).
FAILED - RETRYING: check host where ingress controller is running (3 retries left).
FAILED - RETRYING: check host where ingress controller is running (2 retries left).
FAILED - RETRYING: check host where ingress controller is running (1 retries left).
fatal: [taco-aio -> taco-aio]: FAILED! => {"attempts": 10, "changed": true, "cmd": **"/usr/local/bin/kubectl describe ep ingress -n openstack | grep Addresses | grep -v NotReady | awk '{split($2,a,\",\");print a[1]\"\\n\"a[2]\"\\n\"a[3]}' | awk NF", "delta": "0:00:00.086261", "end": "2019-08-09 14:57:48.396029", "rc": 0, "start": "2019-08-09 14:57:48.309768", "stderr": "Error from server (NotFound): endpoints \"ingress\" not found", "stderr_lines": ["Error from server (NotFound): endpoints \"ingress\" not found"], "stdout": "", "stdout_lines": []}**

NO MORE HOSTS LEFT **********************************************************************************************************
	to retry, use: --limit @/root/tacoplay/site.retry

PLAY RECAP ******************************************************************************************************************
taco-aio                   : ok=794  changed=197  unreachable=0    failed=1

INSTALLER STATUS ************************************************************************************************************
Install Ceph Monitor        : Complete (0:00:21)
Install Ceph Manager        : Complete (0:00:16)
Install Ceph OSD            : Complete (0:00:49)
Install Ceph Client         : Complete (0:00:11)

**Comment by hycho96** [comment]
그리고 이전에 나오는  Error를 보면 ignoring  되는 부분이 있고요.
============================================================
TASK [armada/apply : check if extra-vars exists] ****************************************************************************
Friday 09 August 2019  14:54:17 +0900 (0:00:00.135)       0:13:46.094 *********
ok: [taco-aio]

TASK [armada/apply : fail if extra-vars doesn't exist] **********************************************************************
Friday 09 August 2019  14:54:17 +0900 (0:00:00.146)       0:13:46.240 *********

TASK [armada/apply : replace TACO keywords to actual values] ****************************************************************
Friday 09 August 2019  14:54:17 +0900 (0:00:00.036)       0:13:46.277 *********
 [WARNING]: Consider using the replace, lineinfile or template module rather than running 'sed'.  If you need to use command
because replace, lineinfile or template is insufficient you can add 'warn: false' to this command task or set
'command_warnings=False' in ansible.cfg to get rid of this message.

changed: [taco-aio]

TASK [armada/apply : check if /root/tacoplay/inventory/sample/armada-manifest.yaml is ready] ********************************
Friday 09 August 2019  14:54:18 +0900 (0:00:00.138)       0:13:46.416 *********
fatal: [taco-aio]: FAILED! => {"changed": true, "cmd": "grep 'TACO_ADMIN_KEYRING' /root/tacoplay/inventory/sample/armada-manifest.yaml", "delta": "0:00:00.004388", "end": "2019-08-09 14:54:18.170780", "msg": "non-zero return code", "rc": 1, "start": "2019-08-09 14:54:18.166392", "stderr": "", "stderr_lines": [], "stdout": "", "stdout_lines": []}
...ignoring

TASK [armada/apply : fail if /root/tacoplay/inventory/sample/armada-manifest.yaml is not ready] *****************************
Friday 09 August 2019  14:54:18 +0900 (0:00:00.128)       0:13:46.545 *********

TASK [armada/apply : delete test pods in openstack namespace] ***************************************************************
Friday 09 August 2019  14:54:18 +0900 (0:00:00.034)       0:13:46.579 *********
fatal: [taco-aio]: FAILED! => {"changed": true, "cmd": "/usr/local/bin/kubectl get pods -n openstack | grep test | awk '{print $1}' | xargs /usr/local/bin/kubectl delete pods -n openstack", "delta": "0:00:00.151492", "end": "2019-08-09 14:54:18.479796", "msg": "non-zero return code", "rc": 123, "start": "2019-08-09 14:54:18.328304", "stderr": "No resources found.\nerror: resource(s) were provided, but no name, label selector, or --all flag specified", "stderr_lines": ["No resources found.", "error: resource(s) were provided, but no name, label selector, or --all flag specified"], "stdout": "", "stdout_lines": []}
...ignoring

TASK [armada/apply : check host where tiller is running] ********************************************************************
Friday 09 August 2019  14:54:18 +0900 (0:00:00.272)       0:13:46.852 *********
changed: [taco-aio]

TASK [armada/apply : delete armada lock] ************************************************************************************
Friday 09 August 2019  14:54:18 +0900 (0:00:00.215)       0:13:47.067 *********
fatal: [taco-aio]: FAILED! => {"changed": true, "cmd": "/usr/local/bin/kubectl delete lock --all -n kube-system", "delta": "0:00:01.114367", "end": "2019-08-09 14:54:19.936472", "msg": "non-zero return code", "rc": 1, "start": "2019-08-09 14:54:18.822105", "stderr": "error: the server doesn't have a resource type \"lock\"", "stderr_lines": ["error: the server doesn't have a resource type \"lock\""], "stdout": "", "stdout_lines": []}
...ignoring

TASK [armada/apply : get existing armada processes] *************************************************************************
Friday 09 August 2019  14:54:19 +0900 (0:00:01.240)       0:13:48.307 *********
changed: [taco-aio]

TASK [armada/apply : kill existing armada processes] ************************************************************************
Friday 09 August 2019  14:54:20 +0900 (0:00:00.157)       0:13:48.465 *********
============================================================

**Comment by hycho96** [comment]
kubectl 로 상태를 보면
=================================================================
root@org-centos7 sample]# kube
kubeadm  kubectl  kubelet
[root@org-centos7 sample]# kubectl get pod --all-namespaces
NAMESPACE     NAME                                       READY   STATUS             RESTARTS   AGE
kube-system   calico-kube-controllers-64bcb6b94c-99lqd   1/1     Running            0          14m
kube-system   calico-node-t572z                          1/1     Running            0          14m
kube-system   coredns-56bc6b976d-v9m4s                   1/1     Running            0          14m
kube-system   dns-autoscaler-56c969bdb8-fgq76            1/1     Running            0          14m
kube-system   kube-apiserver-taco-aio                    1/1     Running            0          14m
kube-system   kube-controller-manager-taco-aio           1/1     Running            0          14m
kube-system   kube-proxy-h4lsd                           1/1     Running            0          14m
kube-system   kube-scheduler-taco-aio                    1/1     Running            0          14m
kube-system   kubernetes-dashboard-6c7466966c-m4f5k      0/1     CrashLoopBackOff   7          14m
kube-system   nodelocaldns-6bnwx                         1/1     Running            0          14m
kube-system   rbd-provisioner-55f79c4cf4-zj8jw           0/1     CrashLoopBackOff   7          14m
kube-system   tiller-deploy-86c8b7897c-wk9gr             1/1     Running            0          14m
[root@org-centos7 sample]#
==================================================================

**Comment by hycho96** [comment]
[root@taco-aio ~]# kubectl get pod --all-namespaces
NAMESPACE     NAME                                       READY   STATUS             RESTARTS   AGE
kube-system   calico-kube-controllers-64bcb6b94c-99lqd   1/1     Running            4          4h5m
kube-system   calico-node-t572z                          1/1     Running            4          4h5m
kube-system   coredns-56bc6b976d-v9m4s                   1/1     Running            1          4h4m
kube-system   dns-autoscaler-56c969bdb8-fgq76            1/1     Running            1          4h4m
kube-system   kube-apiserver-taco-aio                    1/1     Running            4          4h5m
kube-system   kube-controller-manager-taco-aio           1/1     Running            1          4h5m
kube-system   kube-proxy-h4lsd                           1/1     Running            1          4h5m
kube-system   kube-scheduler-taco-aio                    1/1     Running            1          4h5m
kube-system   kubernetes-dashboard-6c7466966c-m4f5k      0/1     CrashLoopBackOff   48         4h4m
kube-system   nodelocaldns-6bnwx                         1/1     Running            1          4h4m
kube-system   rbd-provisioner-55f79c4cf4-zj8jw           0/1     CrashLoopBackOff   47         4h5m
kube-system   tiller-deploy-86c8b7897c-wk9gr             1/1     Running            1          4h4m
[root@taco-aio ~]# kube
kubeadm  kubectl  kubelet
[root@taco-aio ~]# kb
-bash: kb: command not found
[root@taco-aio ~]# kubectl describe pod kubernetes-dashboard-6c7466966c-m4f5k -n kube-system
Name:               kubernetes-dashboard-6c7466966c-m4f5k
Namespace:          kube-system
Priority:           2000000000
PriorityClassName:  system-cluster-critical
Node:               taco-aio/192.168.70.161
Start Time:         Fri, 09 Aug 2019 14:51:23 +0900
Labels:             k8s-app=kubernetes-dashboard
                    pod-template-hash=6c7466966c
Annotations:        <none>
Status:             Running
IP:                 10.233.124.7
Controlled By:      ReplicaSet/kubernetes-dashboard-6c7466966c
Containers:
  kubernetes-dashboard:
    Container ID:  docker://a7409acfcd14412d7b90850e27528568d68a78ef50c3ff863f000480cb7e3045
    Image:         gcr.io/google_containers/kubernetes-dashboard-amd64:v1.10.1
    Image ID:      docker-pullable://gcr.io/google_containers/kubernetes-dashboard-amd64@sha256:0ae6b69432e78069c5ce2bcde0fe409c5c4d6f0f4d9cd50a17974fea38898747
    Port:          8443/TCP
    Host Port:     0/TCP
    Args:
      --auto-generate-certificates
      --authentication-mode=token
      --token-ttl=900
    State:          Waiting
      Reason:       CrashLoopBackOff
    Last State:     Terminated
      Reason:       Error
      Exit Code:    1
      Started:      Fri, 09 Aug 2019 18:52:00 +0900
      Finished:     Fri, 09 Aug 2019 18:52:01 +0900
    Ready:          False
    Restart Count:  48
    Limits:
      cpu:     100m
      memory:  256M
    Requests:
      cpu:        50m
      memory:     64M
    Liveness:     http-get https://:8443/ delay=0s timeout=1s period=10s #success=1 #failure=3
    Environment:  <none>
    Mounts:
      /certs from kubernetes-dashboard-certs (rw)
      /tmp from tmp-volume (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from kubernetes-dashboard-token-q58p6 (ro)
Conditions:
Type              Status
  Initialized       True
  Ready             False
  ContainersReady   False
  PodScheduled      True
Volumes:
  kubernetes-dashboard-certs:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  kubernetes-dashboard-certs
    Optional:    false
  tmp-volume:
    Type:       EmptyDir (a temporary directory that shares a pod's lifetime)
    Medium:
    SizeLimit:  <unset>
  kubernetes-dashboard-token-q58p6:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  kubernetes-dashboard-token-q58p6
    Optional:    false
QoS Class:       Burstable
Node-Selectors:  <none>
Tolerations:     node-role.kubernetes.io/master:NoSchedule
                 node.kubernetes.io/not-ready:NoExecute for 300s
                 node.kubernetes.io/unreachable:NoExecute for 300s
Events:
  Type     Reason   Age                    From               Message
  ----     ------   ----                   ----               -------
  Normal   Pulled   47m (x41 over 4h5m)    kubelet, taco-aio  Container image "gcr.io/google_containers/kubernetes-dashboard-amd64:v1.10.1" already present on machine
  Warning  BackOff  40s (x1027 over 4h5m)  kubelet, taco-aio  Back-off restarting failed container
===================================================================
root@taco-aio ~]# kubectl describe pod rbd-provisioner-55f79c4cf4-zj8jw -n kube-system
Name:               rbd-provisioner-55f79c4cf4-zj8jw
Namespace:          kube-system
Priority:           2000000000
PriorityClassName:  system-cluster-critical
Node:               taco-aio/192.168.70.161
Start Time:         Fri, 09 Aug 2019 14:51:17 +0900
Labels:             app=rbd-provisioner
                    pod-template-hash=55f79c4cf4
                    version=v2.1.1-k8s1.11
Annotations:        <none>
Status:             Running
IP:                 10.233.124.8
Controlled By:      ReplicaSet/rbd-provisioner-55f79c4cf4
Containers:
  rbd-provisioner:
    Container ID:  docker://7bf3d09c57a2fc02e277d497f5d1b92d828a8a5850dd144f38e5f456fbaa835c
    Image:         quay.io/external_storage/rbd-provisioner:v2.1.1-k8s1.11
    Image ID:      docker-pullable://quay.io/external_storage/rbd-provisioner@sha256:f0f6949c61388b043f140ec535dcf6ca5fffd8654d664d2d68bdf96bf52aa362
    Port:          <none>
    Host Port:     <none>
    Command:
      /usr/local/bin/rbd-provisioner
    Args:
      -id=${POD_NAME}
    State:          Waiting
      Reason:       CrashLoopBackOff
    Last State:     Terminated
      Reason:       Error
      Exit Code:    255
      Started:      Fri, 09 Aug 2019 18:56:54 +0900
      Finished:     Fri, 09 Aug 2019 18:56:55 +0900
    Ready:          False
    Restart Count:  48
    Environment:
      PROVISIONER_NAME:  ceph.com/rbd
      POD_NAME:          rbd-provisioner-55f79c4cf4-zj8jw (v1:metadata.name)
    Mounts:
      /var/run/secrets/kubernetes.io/serviceaccount from rbd-provisioner-token-9pcz8 (ro)
Conditions:
  Type              Status
  Initialized       True
  Ready             False
  ContainersReady   False
  PodScheduled      True
Volumes:
  rbd-provisioner-token-9pcz8:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  rbd-provisioner-token-9pcz8
    Optional:    false
QoS Class:       BestEffort
Node-Selectors:  <none>
Tolerations:     node.kubernetes.io/not-ready:NoExecute for 300s
                 node.kubernetes.io/unreachable:NoExecute for 300s
Events:
  Type     Reason   Age                      From               Message
  ----     ------   ----                     ----               -------
  Warning  BackOff  3m56s (x1001 over 4h8m)  kubelet, taco-aio  Back-off restarting failed container

**Comment by JohnHaan** [comment]
kubernetes-dashboard와 rbd-provisioner POD가 에러가 나는게 근본적인 원인인 것으로 보입니다

**Comment by hycho96** [comment]
OS 설치시나 사전에 해야하는 작업들이 있나요?
AIO 그대로 했는데 이런 상황이라서요.

tacosplay로 설치하면 위와 같이 에러가 나고
kubesplay로 k8s 설치하면, k8s  잘 돌아 갑니다.

**Comment by hycho96** [comment]
위 현상은 iptables 관련 문제였던 것 같습니다.
JohnHaan님 많은 도움 주셔서 감사드립니다. ^^
