### ISSUE TITLE
cluster-api 도입을 포함한 개선 방향

### ISSUE THREAD

**Issue by zugwan** [openinfradev/tacoplay#53]
목표와 TODO가 혼합되어 있으며 정제가 필요합니다.

- 노드 구성, OS 설치/설정 + kubespray 대체
    - cluster-api: 클러스터 배포
    - CNI 설정/설치 필요
    - 추가로 K8S 클러스터에 필요한 것들은?
        - API 서버 LB
- provider target 지원
    - Management 클러스터 환경 구성을 위한 방법
        - OpenStack
        - Metal3
- 사이트 별 환경 설정을 관리하는 방법
- UI 지원

**Comment by Jaesang** [comment]
Management 클러스터 아이디어

- 구축형
1. target 클러스터 배포를 위해 사이트에 management 클러스터를 우선 배포 후 사용
- 구독형
1. 여러 가입자의 클러스터를 관리하는 하나의 관리클러스터 운영
2. 운영자만 관리
3. 가입자별 자원 분리 필요

**Comment by Jaesang** [comment]
TODO
- 현상황에 맞게 Usecase 업데이트
- Usecase 검증: cluster-api에서 지원되는 기능인지 개발이 필요한 기능인지 확인
- 개발 필요 부분에 대해 로드맵 작성

**Comment by bluejayKR** [comment]
Cluster-API 기반의 프로젝트는 tacoplay와 별도의 프로젝트로 진행 예정으로, 이 이슈는 Close 하겠습니다.
