### ISSUE TITLE
1.20 버전에서 "selfLink was empty, can't make reference" 에러 발생

### ISSUE THREAD

**Issue by intelliguy** [openinfradev/tacoplay#54]
kubernetes 1.20 버전부터 SelfLink에 변화가 있습니다.
현재 TACO(hanu)에서 사용하는 것 중에서 rbd-provisioner가 직접적으로 영향을 받습니다.
https://stackoverflow.com/questions/65376314/kubernetes-nfs-provider-selflink-was-empty
20버전에서는 우회방법을 지원하지만 21버전에서는 아예 삭제된다고 합니다. 이에따라 대응이 필요합니다.

20버전에서 우회방법은 kube-api의 manifest 파일(/etc/kubernetes/manifests/kube-apiserver.yaml)에 - --feature-gates=RemoveSelfLink=false 옵션을 추가하는 것입니다.
https://github.com/kubernetes-sigs/nfs-subdir-external-provisioner/issues/25

**Comment by zugwan** [comment]
ceph-ansible, rbd-provisioner를 rook로 대체하는 것을 진행하는 것이 좋을 듯 합니다.
