### ISSUE TITLE
TACO-Kubernetes Upgrade 패턴

### ISSUE THREAD

**Issue by prudentcircle** [openinfradev/tacoplay#69]
안녕하세요!

정신을 차려보니 Kubernetes의 API 인증서가 만료가 되어버려서...ㅜ.ㅜ
K8S Documentation을 찾아보던 중, Kubespray의 discussion 내용을 보면 
어차피 6개월 - 12개월 주기의 업그레이드를 권장 하기 때문에 인증서 교체를 고민할 필요가 없다는 내용이 나오는데요,
[DISCUSSION LINK](https://github.com/kubernetes-sigs/kubespray/issues/7104)

Kubespray의 업그레이드 매뉴얼에 따르면, Kubespray Tag 한 개씩 단계별로 업데이트 하는것을 권장하고 있습니다.
[Kubespray-Upgrades.md](https://github.com/kubernetes-sigs/kubespray/blob/master/docs/upgrades.md)

TACO를 사용한 Kubernetes의 업그레이드 절차는 그럼 아래와 같이 될까요?

1. VERSIONS 파일에서 kubespray의 버전 수정 (저의 경우에는 v2.13 -> v2.14 로 수정 하게 될것 같습니다)
2. fetch-sub-projects.sh 실행
3. upgrade-cluster.yml 실행

아무래도 클러스터 업그레이드에 대한 내용이 아래 Documentation에 녹아들어가야 하지 않을까 싶지만,
https://taco-docs.readthedocs.io/ko/latest/

일단은 제가 제시한 저 절차가 K8S 업그레이드를 진행할때 유효한지 궁금합니다

**Comment by Jaesang** [comment]
안녕하세요~ 기본적으로 kubespray안에 있는 `kube_version` 변수값을 통해 k8s 버전이 정해질거라 kubespray 2.13에서 지원하는 kube_version중 대원님 kube보다 상위 버전으로 변경하고 upgrade_cluster를 돌리는게 가장 쉬운 방법이 아닐까합니다.
`fetch-sub-projcets.sh`는 `VERSIONS`파일 읽어서 git repo 땡겨오는거라 굳이 돌려야하나 싶네요

**Comment by prudentcircle** [comment]
> 안녕하세요~ 기본적으로 kubespray안에 있는 `kube_version` 변수값을 통해 k8s 버전이 정해질거라 kubespray 2.13에서 지원하는 kube_version중 대원님 kube보다 상위 버전으로 변경하고 upgrade_cluster를 돌리는게 가장 쉬운 방법이 아닐까합니다.
> `fetch-sub-projcets.sh`는 `VERSIONS`파일 읽어서 git repo 땡겨오는거라 굳이 돌려야하나 싶네요

우와. 빠른 답변 감사드립니다!

제가 조금 조심스럽게 접근하게 된 이유는 Kubespray 에서 제공하는 documentation에 아래와 같은 문구가 있어서 입니다 ^^.


>⚠️ Do not skip releases when upgrading--upgrade by one tag at a time. ⚠️
> For instance, if you're on v2.6.0, then check out v2.7.0, run the upgrade, check out the next tag, and run the next upgrade, etc.

이건 단순히 Kubernetes 상위 버전으로 업그레이드 하는것과는 조금 뉘앙스가 달라서 문의를 드려보게 되었습니다. ^^.
그리고 upgrade-cluster.yml은 아무래도 아래와 같이 host와 extra-vars가 다 적용해서 실행하는게 좋겠죠?

```
ansible-playbook -b -i inventory/hosts.ini -e @inventory/extra-vars.yml upgrade-cluster.yml
```

**Comment by Jaesang** [comment]
@prudentcircle 네, extra-vars에 옵션들이 들어가야하니 저 파일에 업그레이드 관련 변수를 선언하고 실행하는게 좋습니다.
