### ISSUE TITLE
Offline용 아카이브 만들 때 컨테이너 이미지의 태그 변경 이슈

### ISSUE THREAD

**Issue by Jaesang** [openinfradev/tacoplay#84]
Offline용 아카이브를 만들 때 site-prepare playbook을 실행하면 local registry tacorepo:5000에 이미지를 저장하고 저장된 이미지를 포함한 tacoplay 폴더를 압축합니다.

taco에서 사용하는 수많은 이미지를 모두 local registry에 저장하는 과정에서 image name, url이 여러 케이스가 존재함에 따라 `scripts/tag-images.sh`를 통해 외부 이미지를 local 이미지로 태그를 변경하게 됩니다.

`scripts/tag-images.sh`에 내용을 보면 local에 저장된 모든 이미지를 파싱하는데, 이 때 `<owner>/<image name>`형식으로된 이미지를 `<image name>`만 살려서 저장합니다. 모든 이미지를 다 그렇게 하는 것은 아니고 특정 owner에 대해 건별로 처리하고 있습니다.
https://github.com/openinfradev/tacoplay/blob/22d09c0acebb6a19e17152ade38dd01ef6cfa389/scripts/tag-images.sh#L12-L32

예를 들어 `siim/kubernetes-event-exporter:0.1.0`이미지는 스크립트를 통해 `tacorepo:5000/kubernetes-event-exporter:0.1.0`로 저장됩니다.

local registry에서 owner를 표기할 수 있기 때문에 위에 처럼 owner를 지운채로 저장하기 보다는 owner를 살려서 저장하는 것으로 변경해야 추후 이미지 원본을 추적할 수 있을 것입니다.

owner를 지울 수 밖에 없었던 이유가 없다면, owner를 지우는 부분을 삭제하고 owner를 포함하여 Local registry에 저장하는 것을 건의합니다.

**Comment by bluejayA** [comment]
이 이슈는 Close 해도 되는걸까요?

**Comment by Jaesang** [comment]
@bluejayA 개선은 해야하는데 당장의 이슈가 아니다보니 우선순위가 낮네요

**Comment by bluejayA** [comment]
"revisit" 같은 레이블 달고 close 상태로 놔두었다가, 실제로 다시 할때 reopen해도 되지 않을까요? 
근데 레이블은 뭐가 적당할지 의견은 주시면 감사.

**Comment by Jaesang** [comment]
kubernetes 프로젝트를 보니 stale뒤 rotten과 frozen으로 나누어 관리하는것 같네요.
이 경우에는 frozen이라 생각됩니다. 

https://github.com/kubernetes/kubernetes/labels?q=lifecycle

**Comment by bluejayA** [comment]
lifecycle/active, lifecycle/stale, lifecycle/frozen, lifecycle/rotten.. 우리도 이거 그대로 차용해도 나쁘지 않을듯.
