### ISSUE TITLE
osd_scenario: lvm devices: 사용 Error

### ISSUE THREAD

**Issue by hycho96** [openinfradev/tacoplay#9]
**Bug Report**
osd_scenario: lvm 
devices: 로 지정하면 Error 발생합니다.

=============================================
vim extra-vars.yml
osd_scenario: lvm
devices:
  - /dev/sda
  - /dev/sdb
  - /dev/nvme0n1

다음과 같이 Error 
TASK [Assert ceph OSD specific variables when deploying new ceph] *************************************************************************************
task path: /root/tacoplay/site-assert.yml:113
Friday 30 August 2019  09:58:26 +0900 (0:00:00.412)       0:00:01.493 *********
failed: [ceph001-storage] (item=lvm_volumes) => {
    "assertion": "lvm_volumes is defined",
    "changed": false,
    "evaluated_to": false,
    "item": "lvm_volumes"
}
failed: [ceph002-storage] (item=lvm_volumes) => {
    "assertion": "lvm_volumes is defined",
    "changed": false,
    "evaluated_to": false,
    "item": "lvm_volumes"
}
failed: [ceph003-storage] (item=lvm_volumes) => {
    "assertion": "lvm_volumes is defined",
    "changed": false,
    "evaluated_to": false,
    "item": "lvm_volumes"
}
	to retry, use: —limit @/root/tacoplay/site.retry

/root/tacoplay/site-assert.yml 여기서 막고 있네요. 

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] : CentOS 7 
 - Version [e.g. 22] : taco latest

**Comment by zugwan** [comment]
'devices' 대신 'lvm_volumes' 사용하셔야 합니다.
```
lvm_volumes:
  - data: /dev/sda
  - data: /dev/sdb
```
또한, 'osd_scenario: lvm'은 vars/global_ceph.yml에 기본값으로 이미 정의되어 있기 때문에 필요하지 않습니다.
